# Este workflow se activa en cada push a la rama 'master'
name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ master ] # Puedes cambiarlo a 'main' si usas esa rama

# Variables de entorno para que el workflow sea fácil de adaptar
env:
  # Cambia estos valores para cada microservicio
  IMAGE_NAME: pierodevjar/tms-api-gateway
  DEPLOYMENT_NAME: api-gateway
  KUBE_NAMESPACE: tms-backend

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to Kubernetes Cluster
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install oidc-login plugin
        run: |
          curl -sSL "https://github.com/int128/kubelogin/releases/download/v1.28.1/kubelogin_linux_amd64.zip" -o kubelogin.zip
          unzip kubelogin.zip
          sudo mv kubelogin /usr/local/bin/

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > ~/.kube/config
          kubectl config use-context tms-backend-stack-dliriotech-apis-production-oidc

      # 4. Despliega la nueva imagen en Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ env.IMAGE_NAME }}:$(echo ${{ github.sha }} | cut -c1-7) -n ${{ env.KUBE_NAMESPACE }}

      - name: Verify deployment rollout
        run: kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.KUBE_NAMESPACE }} --timeout=120s